// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: peer/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetPeerRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetPeerRequest) Reset()         { *m = QueryGetPeerRequest{} }
func (m *QueryGetPeerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPeerRequest) ProtoMessage()    {}
func (*QueryGetPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d45bcf7fe2423301, []int{0}
}
func (m *QueryGetPeerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPeerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPeerRequest.Merge(m, src)
}
func (m *QueryGetPeerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPeerRequest proto.InternalMessageInfo

func (m *QueryGetPeerRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetPeerResponse struct {
	Peer *Peer `protobuf:"bytes,1,opt,name=Peer,proto3" json:"Peer,omitempty"`
}

func (m *QueryGetPeerResponse) Reset()         { *m = QueryGetPeerResponse{} }
func (m *QueryGetPeerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPeerResponse) ProtoMessage()    {}
func (*QueryGetPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d45bcf7fe2423301, []int{1}
}
func (m *QueryGetPeerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPeerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPeerResponse.Merge(m, src)
}
func (m *QueryGetPeerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPeerResponse proto.InternalMessageInfo

func (m *QueryGetPeerResponse) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

type QueryAllPeerRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPeerRequest) Reset()         { *m = QueryAllPeerRequest{} }
func (m *QueryAllPeerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPeerRequest) ProtoMessage()    {}
func (*QueryAllPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d45bcf7fe2423301, []int{2}
}
func (m *QueryAllPeerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPeerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPeerRequest.Merge(m, src)
}
func (m *QueryAllPeerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPeerRequest proto.InternalMessageInfo

func (m *QueryAllPeerRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPeerResponse struct {
	Peer       []*Peer             `protobuf:"bytes,1,rep,name=Peer,proto3" json:"Peer,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPeerResponse) Reset()         { *m = QueryAllPeerResponse{} }
func (m *QueryAllPeerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPeerResponse) ProtoMessage()    {}
func (*QueryAllPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d45bcf7fe2423301, []int{3}
}
func (m *QueryAllPeerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPeerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPeerResponse.Merge(m, src)
}
func (m *QueryAllPeerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPeerResponse proto.InternalMessageInfo

func (m *QueryAllPeerResponse) GetPeer() []*Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *QueryAllPeerResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetPeerRequest)(nil), "liubaninc.m1.peer.QueryGetPeerRequest")
	proto.RegisterType((*QueryGetPeerResponse)(nil), "liubaninc.m1.peer.QueryGetPeerResponse")
	proto.RegisterType((*QueryAllPeerRequest)(nil), "liubaninc.m1.peer.QueryAllPeerRequest")
	proto.RegisterType((*QueryAllPeerResponse)(nil), "liubaninc.m1.peer.QueryAllPeerResponse")
}

func init() { proto.RegisterFile("peer/query.proto", fileDescriptor_d45bcf7fe2423301) }

var fileDescriptor_d45bcf7fe2423301 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x6b, 0xdb, 0x30,
	0x1c, 0xc5, 0xe3, 0x6c, 0xd9, 0x98, 0x76, 0xd8, 0xa6, 0x05, 0xb2, 0x85, 0xe1, 0x6c, 0x3e, 0x24,
	0x63, 0x61, 0x12, 0xce, 0x3e, 0x41, 0x36, 0x58, 0x7a, 0x4c, 0x73, 0x2c, 0xf4, 0x20, 0x27, 0x7f,
	0x5c, 0x53, 0x5b, 0x72, 0x2c, 0xb9, 0x34, 0x84, 0x42, 0xe9, 0xa5, 0x97, 0x1e, 0x0a, 0xfd, 0x52,
	0x3d, 0x06, 0x7a, 0xe9, 0xb1, 0x24, 0xfd, 0x20, 0xc5, 0x92, 0x49, 0x9d, 0x26, 0x21, 0x17, 0x83,
	0xec, 0xf7, 0xfe, 0xef, 0xf7, 0xd7, 0x33, 0xfa, 0x18, 0x03, 0x24, 0x74, 0x9c, 0x42, 0x32, 0x21,
	0x71, 0x22, 0x94, 0xc0, 0x9f, 0xc2, 0x20, 0xf5, 0x18, 0x0f, 0xf8, 0x90, 0x44, 0x2e, 0xc9, 0x3e,
	0xd7, 0xbf, 0xf9, 0x42, 0xf8, 0x21, 0x50, 0x16, 0x07, 0x94, 0x71, 0x2e, 0x14, 0x53, 0x81, 0xe0,
	0xd2, 0x18, 0xea, 0xbf, 0x86, 0x42, 0x46, 0x42, 0x52, 0x8f, 0x49, 0x30, 0x93, 0xe8, 0x89, 0xeb,
	0x81, 0x62, 0x2e, 0x8d, 0x99, 0x1f, 0x70, 0x2d, 0xce, 0xb5, 0x1f, 0x74, 0x5c, 0xf6, 0x30, 0x2f,
	0x9c, 0x36, 0xfa, 0xbc, 0x9f, 0x59, 0x7a, 0xa0, 0xfa, 0x00, 0xc9, 0x00, 0xc6, 0x29, 0x48, 0x85,
	0xab, 0xa8, 0x12, 0xf0, 0x11, 0x9c, 0x7e, 0xb1, 0xbe, 0x5b, 0x3f, 0xdf, 0x0d, 0xcc, 0xc1, 0xf9,
	0x87, 0xaa, 0xab, 0x62, 0x19, 0x0b, 0x2e, 0x01, 0xb7, 0xd1, 0xeb, 0xec, 0xac, 0xc5, 0xef, 0x3b,
	0x35, 0xb2, 0xb6, 0x01, 0xd1, 0x72, 0x2d, 0x72, 0x0e, 0xf3, 0xc4, 0x6e, 0x18, 0x16, 0x13, 0xff,
	0x23, 0xf4, 0x4c, 0x9b, 0x4f, 0x6a, 0x12, 0xb3, 0x1a, 0xc9, 0x56, 0x23, 0xe6, 0x92, 0xf2, 0xd5,
	0x48, 0x9f, 0xf9, 0x90, 0x7b, 0x07, 0x05, 0xa7, 0x73, 0x65, 0xe5, 0x90, 0xcb, 0xf9, 0x6b, 0x90,
	0xaf, 0x76, 0x42, 0xe2, 0xde, 0x0a, 0x4d, 0x59, 0xd3, 0xb4, 0x76, 0xd2, 0x98, 0xa4, 0x22, 0x4e,
	0xe7, 0xb2, 0x8c, 0x2a, 0x1a, 0x07, 0x9f, 0x5b, 0x06, 0x00, 0x37, 0x37, 0x44, 0x6f, 0xe8, 0xa0,
	0xde, 0xda, 0xa9, 0x33, 0x79, 0x4e, 0xeb, 0xe2, 0xee, 0xf1, 0xa6, 0xfc, 0x03, 0x37, 0xe8, 0xd2,
	0x40, 0x23, 0x97, 0x2e, 0xab, 0xa6, 0x53, 0x5d, 0xdf, 0x19, 0x9e, 0xa2, 0xb7, 0x99, 0xb1, 0x1b,
	0x86, 0xdb, 0x21, 0x56, 0x6b, 0xd9, 0x0e, 0xf1, 0xe2, 0x7a, 0x9d, 0x86, 0x86, 0xf8, 0x8a, 0x6b,
	0x5b, 0x20, 0xfe, 0xee, 0xdd, 0xce, 0x6d, 0x6b, 0x36, 0xb7, 0xad, 0x87, 0xb9, 0x6d, 0x5d, 0x2f,
	0xec, 0xd2, 0x6c, 0x61, 0x97, 0xee, 0x17, 0x76, 0xe9, 0x80, 0xf8, 0x81, 0x3a, 0x4a, 0x3d, 0x32,
	0x14, 0x51, 0xc1, 0x2c, 0x47, 0xc7, 0xbf, 0x7d, 0x41, 0x23, 0x31, 0x4a, 0x43, 0x90, 0x66, 0x90,
	0x9a, 0xc4, 0x20, 0xbd, 0x37, 0xfa, 0xd7, 0xfd, 0xf3, 0x14, 0x00, 0x00, 0xff, 0xff, 0x13, 0x37,
	0x7f, 0xd3, 0x3c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a peer by index.
	Peer(ctx context.Context, in *QueryGetPeerRequest, opts ...grpc.CallOption) (*QueryGetPeerResponse, error)
	// Queries a list of peer items.
	PeerAll(ctx context.Context, in *QueryAllPeerRequest, opts ...grpc.CallOption) (*QueryAllPeerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Peer(ctx context.Context, in *QueryGetPeerRequest, opts ...grpc.CallOption) (*QueryGetPeerResponse, error) {
	out := new(QueryGetPeerResponse)
	err := c.cc.Invoke(ctx, "/liubaninc.m1.peer.Query/Peer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PeerAll(ctx context.Context, in *QueryAllPeerRequest, opts ...grpc.CallOption) (*QueryAllPeerResponse, error) {
	out := new(QueryAllPeerResponse)
	err := c.cc.Invoke(ctx, "/liubaninc.m1.peer.Query/PeerAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a peer by index.
	Peer(context.Context, *QueryGetPeerRequest) (*QueryGetPeerResponse, error)
	// Queries a list of peer items.
	PeerAll(context.Context, *QueryAllPeerRequest) (*QueryAllPeerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Peer(ctx context.Context, req *QueryGetPeerRequest) (*QueryGetPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Peer not implemented")
}
func (*UnimplementedQueryServer) PeerAll(ctx context.Context, req *QueryAllPeerRequest) (*QueryAllPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeerAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Peer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Peer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liubaninc.m1.peer.Query/Peer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Peer(ctx, req.(*QueryGetPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PeerAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PeerAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liubaninc.m1.peer.Query/PeerAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PeerAll(ctx, req.(*QueryAllPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "liubaninc.m1.peer.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Peer",
			Handler:    _Query_Peer_Handler,
		},
		{
			MethodName: "PeerAll",
			Handler:    _Query_PeerAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peer/query.proto",
}

func (m *QueryGetPeerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPeerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPeerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPeerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPeerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPeerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Peer != nil {
		{
			size, err := m.Peer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPeerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPeerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPeerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPeerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPeerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPeerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Peer) > 0 {
		for iNdEx := len(m.Peer) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Peer[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetPeerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPeerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPeerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPeerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Peer) > 0 {
		for _, e := range m.Peer {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetPeerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPeerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPeerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPeerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPeerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPeerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &Peer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPeerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPeerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPeerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPeerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPeerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPeerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Peer = append(m.Peer, &Peer{})
			if err := m.Peer[len(m.Peer)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
